/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_chaozhouzhang_ndklearning_NdkJni */

#ifndef _Included_me_chaozhouzhang_ndklearning_NdkJni
#define _Included_me_chaozhouzhang_ndklearning_NdkJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_chaozhouzhang_ndklearning_NdkJni
 * Method:    ndkJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_me_chaozhouzhang_ndklearning_NdkJni_callNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
